### ISSUE TITLE
Make libpcsc-lite also work on fedora

### ISSUE THREAD

**Issue by Sorunome** [flathub/de.bund.ausweisapp.ausweisapp2#22]
pcsc works by a server-client architecture, where they communicate with each other. Inside the flatpak is only the client, thus "pcsc-lite". Now, the internal protocol for the communication is rather rigid. Most distros just compile pcsc with the default options for possible amount of smartcards, fedora, however, does not. That leads to the normally compiled pcsc-lite in this flatpak being incompatible on fedora hosts. This is a [known issue](https://ludovicrousseau.blogspot.com/2022/02/fedora-flatpak-and-pcsc-lite.html), with no clear/easy fix on the horizon. Soru played around with pcsc for some other flat-packing and came up with a solution to still work on more hosts: Compiling both versions of pcsc-lite and determining in the runtime which one to load. Sadly sorus bash knowledge is not too good so she could only think of how to test for host system name, and not actual features.

Anyhow, the solution to compile both in is here:

```yaml
  - name: pcsc-lite
    sources:
      - type: archive
        url: https://pcsclite.apdu.fr/files/pcsc-lite-1.9.9.tar.bz2
        sha256: cbcc3b34c61f53291cecc0d831423c94d437b188eb2b97b7febc08de1c914e8a
    config-opts:
      - --disable-libudev
      - --disable-libsystemd
      - --without-systemdsystemunitdir
      - --disable-serial
      - --disable-usb
      - --disable-documentation
      - --libdir=/app/lib/pcsc-lite
    cleanup:
      - /include
      - /bin/pcsc-spy
      - /lib/pcsc-lite/libpcscspy*
      - /lib/pcsc-lite/pkgconfig
      - /share/doc
      - /share/man
    post-install:
      - rm /app/sbin/pcscd
      - rmdir /app/sbin || true
  - name: pcsc-lite-fedora
    sources:
      - type: archive
        url: https://pcsclite.apdu.fr/files/pcsc-lite-1.9.9.tar.bz2
        sha256: cbcc3b34c61f53291cecc0d831423c94d437b188eb2b97b7febc08de1c914e8a
      - type: patch
        path: pcsc-lite-1.9.1-maxreaders.patch
    config-opts:
      - --disable-libudev
      - --disable-libsystemd
      - --without-systemdsystemunitdir
      - --disable-serial
      - --disable-usb
      - --disable-documentation
      - --libdir=/app/lib/pcsc-lite-fedora
    cleanup:
      - /include
      - /bin/pcsc-spy
      - /lib/pcsc-lite-fedora/libpcscspy*
      - /lib/pcsc-lite-fedora/pkgconfig
      - /share/doc
      - /share/man
    post-install:
      - rm /app/sbin/pcscd
      - rmdir /app/sbin || true
```

And then, to determine what to load, a script to source pre-execution something as following:
```sh
#!/bin/sh
if [[ $(cat /proc/version) =~ "fedora" || $(cat /proc/version) =~ "Red Hat" ]]; then
  echo "fedora"
  LD_LIBRARY_PATH=/app/lib/pcsc-lite-fedora:$LD_LIBRARY_PATH
else
  echo "normal"
  LD_LIBRARY_PATH=/app/lib/pcsc-lite:$LD_LIBRARY_PATH
fi

echo $LD_LIBRARY_PATH
export LD_LIBRARY_PATH

```
